version: '3'

services:
  vite:
    build: ./client/dataStack
    container_name: dataStackVite
    ports:
      - 5173:5173
    volumes:
      - ./client/dataStack:/app
      - /app/node_modules

  notebook:
    image: jupyter/datascience-notebook
    container_name: taller_notebook
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    
  api:
    build: ./api
    container_name: taller_api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app